export const FORM_LOGIN = 'FROM_LOGIN';
/**
 * Get ALL PRODUCTS
 */
export const GET_PRODUCTS_PENDING = 'GET_PRODUCTS_PENDING';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
/**
 * GET INFO PRODUCT
 */
export const GET_INFO_PRODUCTS_PENDING = 'GET_INFO_PRODUCTS_PENDING';
export const GET_INFO_PRODUCTS_SUCCESS = 'GET_INFO_PRODUCTS_SUCCESS';
export const GET_INFO_PRODUCTS_ERROR = 'GET_INFO_PRODUCTS_ERROR';
/**
 * GET PRODUCT GROUP
 */
export const GET_PRODUCTS_GROUP_PENDING = 'GET_PRODUCTS_GROUP_PENDING';
export const GET_PRODUCTS_GROUP_SUCCESS = 'GET_PRODUCTS_GROUP_SUCCESS';
export const GET_PRODUCTS_GROUP_ERROR = 'GET_PRODUCTS_GROUP_ERROR'
/**
 * SEARCH PRODUCT
 */

export const SEARCH_PRODUCT_PENDDING = 'SEARCH_PRODUCT_PENDDING'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_ERROR = 'SEARCH_PRODUCT_ERROR'
export const SEARCH_PRODUCT_TEXT = 'SEARCH_PRODUCT_TEXT'


/**
 * 
 */
export const GET_CATEGORY_PRODUCT_SEARCH = 'GET_CATEGORY_PRODUCT_SEARCH'
export const SELECT_PRODUCTS_SEARCH = 'SELECT_PRODUCTS_SEARCH'


/**
 * LOGIN USER
 */
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
/**
 * REG USER
 */
export const REGSITER_USER_PENDING = 'REGSITER_USER_PENDING'
export const REGSITER_USER_SUCCESS = 'REGSITER_USER_SUCCESS'
export const REGSITER_USER_ERROR = 'REGSITER_USER_ERROR'
/**
/**
* From Login Page
*/
export const LOGOUT_USER_API = 'LOGOUT_USER_API'


export const SHOW_IS_PAGE_FROM = 'SHOW_IS_PAGE_FROM'

/**
 * GET ADDRESS
 */
export const GET_ALL_THANH_PHO = 'GET_ALL_THANH_PHO'
export const GET_ALL_QUAN_HUYEN = 'GET_ALL_QUAN_HUYEN'
export const GET_ALL_XA_PHUONG = 'GET_ALL_XA_PHUONG'

export const GET_ALL_QUAN_HUYEN_CODE_TP = 'GET_ALL_QUAN_HUYEN_CODE_TP'
export const GET_ALL_XA_PHUONG_CODE_QH = 'GET_ALL_XA_PHUONG_CODE_QH'

/**
 * API GET DATA PRODUCT - TYPE -=>
 */
export const GET_ALL_UNIT_PRICE = 'GET_ALL_UNIT_PRICE'
export const GET_ALL_DISCOUNT_PRICE = 'GET_ALL_DISCOUNT_PRICE'
export const GET_ALL_GROUP_PRODUCT = 'GET_ALL_GROUP_PRODUCT'
export const GET_ALL_BUY_PRODUCT = 'GET_ALL_BUY_PRODUCT'
export const GET_ALL_DANH_MUC_SP = 'GET_ALL_DANH_MUC_SP'


/**
 * 
 * POST NHOM SAN PHAM
 */

export const POST_VALUE_NHOM_SP = 'POST_VALUE_NHOM_SP'



export const POST_PRODUCT_PENDING = 'POST_PRODUCT_PENDING'
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS'
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR'

/**
 * 
 */


export const SP_DELETE_PRODUCT = 'SP_DELETE_PRODUCT'
export const FORM_NOTIFICATION_OW = 'FORM_NOTIFICATION_OW'

export const SEARCH_SELECT_PRODUCT = 'SEARCH_SELECT_PRODUCT'


export const GET_ALL_CART_USER = 'GET_ALL_CART_USER'
export const ADD_CART_USER = 'ADD_CART_USER'
export const DELETE_CART_USER = 'DELETE_CART_USER'
export const SP_PAY_BTN_PRODUCT = 'SP_PAY_BTN_PRODUCT'


export const GET_ALL_ORDER_ADMIN_PRODUCTS = 'GET_ALL_ORDER_ADMIN_PRODUCTS'
export const UPDATE_TT_ORDER_PRODUCT = 'UPDATE_TT_ORDER_PRODUCT'
export const UPDATE_PRODUCT_ADMIN = 'UPDATE_PRODUCT_ADMIN'
export const GET_PAGE_DATA = 'GET_PAGE_DATA'
export const GET_PAGE_ORDER_DATA = 'GET_PAGE_ORDER_DATA'
export const GET_ALL_SHIP_CODE_PRODUCT = 'GET_ALL_SHIP_CODE_PRODUCT'
export const GET_PAGE_ORDER_USER_CODE = 'GET_PAGE_ORDER_USER_CODE'